### ISSUE TITLE
Error when opening Map View

### ISSUE THREAD

**Issue by david7411** [gityopie/odoo-addons#108]
I installed the web_google_maps and contacts_map modules, added the google api key and my GEOLOCATE of my customers is working fine (I get the long and lat values)

However when I open the map for 1 customer, I get a blank screen. On the top left I only see the buttons Create and Center Map.
When I open the map on the Contact overview screen I get the following error:
Error:
Uncaught TypeError: Cannot read property 'equals' of undefined

http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1060
Traceback:
TypeError: Cannot read property 'equals' of undefined
    at http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1060:45
    at Array.forEach (<anonymous>)
    at Class._clusterAddMarker (http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1058:34)
    at Class._createMarker [as _super] (http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1048:18)
    at Class._createMarker (http://localhost:8069/google_marker_icon_picker/static/src/js/view/map/map_renderer.js:16:18)
    at Class._createMarker (http://localhost:8069/web/static/src/js/core/class.js:123:38)
    at http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1163:22
    at Function._.each._.forEach (http://localhost:8069/web/static/lib/underscore/underscore.js:145:9)
    at Class._renderUngrouped (http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1159:15)
    at Class._renderMarkers (http://localhost:8069/web_google_maps/static/src/js/view/map/map_renderer.js:1132:22)

I'm using the modules on Odoo 12 enterprise edition.

Has anybody seen this behavior before?

David

**Comment by david7411** [comment]
Found the solution. The Maps Javascript API wasn't enabled.
