### ISSUE TITLE
JS error (V12) when click on button map view

### ISSUE THREAD

**Issue by rolandn** [gityopie/odoo-addons#111]
Erreur:
Uncaught Error: QWeb2: Template 'MapView.buttons' not found

http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3374
Retraçage :
Error: QWeb2: Template 'MapView.buttons' not found
    at Object.exception (http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3374:7)
    at Engine._render (http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3419:103)
    at Engine.render (http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3415:151)
    at Class.renderButtons (http://51.83.68.9:8069/web/content/333-adb64dc/web.assets_backend.js:3193:1023)
    at Class._renderControlPanelElements (http://51.83.68.9:8069/web/content/333-adb64dc/web.assets_backend.js:1291:175)
    at Class.start (http://51.83.68.9:8069/web/content/333-adb64dc/web.assets_backend.js:1283:1427)
    at Class.prototype.(anonymous function) [as start] (http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3538:488)
    at Class.start (http://51.83.68.9:8069/web/content/333-adb64dc/web.assets_backend.js:1548:1042)
    at Class.prototype.(anonymous function) [as start] (http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3538:488)
    at http://51.83.68.9:8069/web/content/272-0dc897c/web.assets_common.js:3684:52

**Comment by gityopie** [comment]
Hi @rolandn 

Thanks for your feedback!
Unfortunately, I cannot reproduce the error on my side

**Comment by wildauwil** [comment]
can i use this in custom module? and if can, what should i write in my xml code? using widget or something?

**Comment by gityopie** [comment]
hi @wildauwil 
yes, you can use it in your custom module.
first you have to define `map` view like any other view (`tree` view, `kanban` view, etc..)
you can find the sample in the module https://github.com/gityopie/odoo-addons/blob/12.0/web_google_maps/views/res_partner.xml.

if you have an issue working with the module or if you want to ask a question
please open a new issue :)

**Comment by AllWorldShops** [comment]
Hi Team,

Im getting the same error. Please check in  Firefox browser.

```


Error: QWeb2: Template 'MapView.buttons' not found

http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3374
Traceback:
exception@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3374:7
_render@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3419:103
render@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3415:151
renderButtons@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:3179:1023
_renderControlPanelElements@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:1275:175
start@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:1267:1427
OdooClass.extend/</prototype[name]</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3537:488
start@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:1518:1018
OdooClass.extend/</prototype[name]</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3537:488
_widgetRenderAndInsert/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3682:52
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
add@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:797:471
then/</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:649
each@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:625:767
then/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:560
Deferred@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:194
then@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:525
_widgetRenderAndInsert@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3681:165
appendTo@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3672:97
_startController@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:486:222
newController/<@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:511:13
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
_createViewController/<@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:496:790
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
updateFunc/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:804:491
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
add@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:797:471
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:772
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
rpc/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3587:448
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
genericJsonRpc/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3556:10
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
done@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:1192:95
callback@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:1212:23


```
