### ISSUE TITLE
No customer locations on the map.

### ISSUE THREAD

**Issue by schinto777** [gityopie/odoo-addons#114]
No customer locations on the map.

In the "view map" view I see what below. I cannot see the objects

![image](https://user-images.githubusercontent.com/55395010/64963102-f9422100-d898-11e9-87d8-9312d462803e.png)

**Comment by gityopie** [comment]
Hi @schinto777 
you have to geolocate your contact first to be able to see them on map

**Comment by schinto777** [comment]
Thank you very much for your answer 
Everything works. Have a nice day 

Pozdrawiam 

Tomasz Schindler 


Od: "Yopi Angi" <notifications@github.com> 
Do: "gityopie/odoo-addons" <odoo-addons@noreply.github.com> 
DW: "Tomasz Schindler" <tomaszschindler@inwemer.pl>, "Mention" <mention@noreply.github.com> 
Wysłane: poniedziałek, 16 września, 2019 19:02:21 
Temat: Re: [gityopie/odoo-addons] No customer locations on the map. (#114) 



Hi [ https://github.com/schinto777 | @schinto777 ] 
you have to geolocate your contact first to be able to see them on map

**Comment by schinto777** [comment]
I have installed Contacts Maps 
The Google Marker Icon Picker, Contacts Maps and Web Google Maps are installed 
And after entering the contact I have an error: 
error: 
QWeb2: Template 'FieldMarkerColorPicker' not found 

https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:3374 
traceback: 
Error: QWeb2: Template 'FieldMarkerColorPicker' not found 
at QWeb2.tools.exception (https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:3374:1) 
at _render (https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:3419:85) 
at render (https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:3415:140) 
at _renderMarker (https://xxxxx.pl/web/content/728-b0a325d/web.assets_backend.js:3306:888) 
at _renderReadonly (https://xxxxx.pl/web/content/728-b0a325d/web.assets_backend.js:3306:840) 
at _render (https://xxxxx.pl/web/content/728-b0a325d/web.assets_backend.js:1048:83) 
at Anonymous function (https://xxxxx.pl/web/content/728-b0a325d/web.assets_backend.js:1045:1509) 
at Anonymous function (https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:802:661) 
at fire (https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:796:278) 
at self.add (https://xxxxx.pl/web/content/702-90a7bad/web.assets_common.js:797:467) 


Please help 

Pozdrawiam 

Tomasz Schindler 


Od: "Yopi Angi" <notifications@github.com> 
Do: "gityopie/odoo-addons" <odoo-addons@noreply.github.com> 
DW: "Tomasz Schindler" <tomaszschindler@inwemer.pl>, "Mention" <mention@noreply.github.com> 
Wysłane: wtorek, 17 września, 2019 9:23:03 
Temat: Re: [gityopie/odoo-addons] No customer locations on the map. (#114) 



Closed [ https://github.com/gityopie/odoo-addons/issues/114 | #114 ] .
