### ISSUE TITLE
 JS error (V12) when click on button map view #111 

### ISSUE THREAD

**Issue by AllWorldShops** [gityopie/odoo-addons#127]
```

Error: QWeb2: Template 'MapView.buttons' not found

http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3374
Traceback:
exception@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3374:7
_render@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3419:103
render@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3415:151
renderButtons@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:3179:1023
_renderControlPanelElements@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:1275:175
start@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:1267:1427
OdooClass.extend/</prototype[name]</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3537:488
start@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:1518:1018
OdooClass.extend/</prototype[name]</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3537:488
_widgetRenderAndInsert/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3682:52
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
add@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:797:471
then/</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:649
each@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:625:767
then/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:560
Deferred@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:194
then@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:525
_widgetRenderAndInsert@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3681:165
appendTo@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3672:97
_startController@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:486:222
newController/<@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:511:13
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
_createViewController/<@http://localhost:10012/web/content/94176-3a63994/web.assets_backend.js:496:790
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
updateFunc/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:804:491
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
add@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:797:471
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:772
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
rpc/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3587:448
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
Deferred/</deferred[tuple[0]]@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:803:56
genericJsonRpc/<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:3556:10
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:681
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
then/</</<@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:802:874
fire@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:796:299
fireWith@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:801:202
done@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:1192:95
callback@http://localhost:10012/web/content/94137-7206712/web.assets_common.js:1212:23
```

```

**Comment by gityopie** [comment]
@AllWorldShops have try to restart your odoo server?
have look at this closed issue https://github.com/gityopie/odoo-addons/issues/124?

let me know if none of the solutions not working.
Thanks

**Comment by augustomurri** [comment]
Hello, same problem, after restarting Odoo server i recice this error
this happen also with "crm map" and "contact maps" modules

`Uncaught TypeError: Cannot read property 'equals' of undefined
https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3062
Traceback:
TypeError: Cannot read property 'equals' of undefined
    at https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3062:358
    at Array.forEach (<anonymous>)
    at Class._clusterAddMarker (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3062:275)
    at Class._createMarker [as _super] (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3062:75)
    at Class._createMarker (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3132:528)
    at Class._createMarker (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:3541:371)
    at https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3064:1674
    at Function._.each._.forEach (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:12:558)
    at Class._renderUngrouped (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3064:1488)
    at Class._renderMarkers (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3064:941)`

**Comment by augustomurri** [comment]
Going on Contact maps, fresh Odoo v12 install with demo data, i recive this error

`Uncaught Error: QWeb2: Template 'FieldMarkerColorPicker' not found
https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:3374
Traceback:
Error: QWeb2: Template 'FieldMarkerColorPicker' not found
    at Object.exception (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:3374:7)
    at Engine._render (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:3419:103)
    at Engine.render (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:3415:151)
    at Class._renderMarker (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3135:907)
    at Class._renderReadonly (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:3135:845)
    at Class._render (https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:1052:95)
    at https://odoo.augustomurri.it/web/content/522-5e8f349/web.assets_backend.js:1049:1521
    at https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:802:681
    at fire (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:796:299)
    at Object.add [as done] (https://odoo.augustomurri.it/web/content/387-3c73411/web.assets_common.js:797:467)`
