### ISSUE TITLE
Module can not be installed in odoo 13 enterprise edition

### ISSUE THREAD

**Issue by MahmoudFahmi** [gityopie/odoo-addons#147]
raise ValidationError(_('Invalid view %s definition in %s') % (view_name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view view.res.partner.map definition in gws_google_maps/views/res_partner.xml

i think there is a conflict between gws_google_maps.map view definition and web_map odoo module that has another map view definition .

**Comment by MahmoudFahmi** [comment]
Note : this issue happens only with enterprise addons

**Comment by gityopie** [comment]
Hi @MahmoudFahmi 

Thanks for open this issue
Unfortunately, that module `gws_google_maps` is not maintain by me
The person or company that published the module on odoo apps copy my module and change the name

**Comment by gityopie** [comment]
Hi @MahmoudFahmi 

The version 13.0 has been published
you can find it on this branch https://github.com/gityopie/odoo-addons/tree/13.0

I'll closed this issue,
Feel free to open new issue if found you error or something doesn't work
Thank you

**Comment by MahmoudFahmi** [comment]
Hi Yopi Angi,

there is always an error while installing the module "web_google_maps" with
odoo 13 enterprise addons , i think the reason is there is a conflict
between your module and "web_map" module included in odoo enterprise addons
, the conflict is in map view definition ,

ex: "Invalid view view.res.partner.map definition in
web_google_maps/views/res_partner.xml"

note that the module working fine and full functionality eit odoo 13 community

Thank you .

**Comment by gityopie** [comment]
Hi @MahmoudFahmi 

Could you please copy-paste the full error message here?

**Comment by MahmoudFahmi** [comment]
Odoo Server Error

Traceback (most recent call last):
  File "/home/../../13/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/../../13/odoo/odoo/models.py", line 4104, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/../../13/odoo/odoo/models.py", line 4018, in _load_records_create
    return self.create(values)
  File "<decorator-gen-175>", line 2, in create
  File "/home/../../13/odoo/odoo/api.py", line 317, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/../../13/odoo/odoo/api.py", line 317, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/../../13/odoo-13.0+e.20200916/odoo/addons/web_studio/models/studio_mixin.py",
line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-31>", line 2, in create
  File "/home/../../13/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/../../13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/../../13/odoo/odoo/models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/../../13/odoo/odoo/fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 299, in _inverse_arch
    view.write(data)
  File "/home/../../13/odoo/addons/w..ite_theme_install/models/theme_models.py",
line 226, in write
    res = super(IrUiView, other_views).write(vals)
  File "/home/../../13/odoo/addons/w..ite/models/ir_ui_view.py", line
51, in write
    return super(View, self).write(vals)
  File "/home/../../13/odoo-13.0+e.20200916/odoo/addons/web_studio/models/studio_mixin.py",
line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/../../13/odoo/odoo/models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/home/../../13/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 406, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') %
(view_name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view view.res.partner.map
definition in web_google_maps/views/res_partner.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/../../13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/../../13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/../../13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/../../13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/../../13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/../../13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/../../13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/../../13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/../../13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/../../13/odoo/addons/web/controllers/main.py", line
1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/../../13/odoo/addons/web/controllers/main.py", line
1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/../../13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/../../13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/home/../../13/odoo/odoo/addons/base/models/ir_module.py",
line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/../../13/odoo/odoo/addons/base/models/ir_module.py",
line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/../../13/odoo/odoo/addons/base/models/ir_module.py",
line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/../../13/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/../../13/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/../../13/odoo/odoo/modules/loading.py", line 315, in
load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/../../13/odoo/odoo/modules/loading.py", line 225, in
load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/../../13/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode,
noupdate, kind, report)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 803, in
convert_xml_import
    obj.parse(doc.getroot())
  File "/home/../../13/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/home/../../13/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/../../13/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/../../13/odoo/odoo/models.py", line 4104, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/../../13/odoo/odoo/models.py", line 4018, in _load_records_create
    return self.create(values)
  File "<decorator-gen-175>", line 2, in create
  File "/home/../../13/odoo/odoo/api.py", line 317, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/../../13/odoo/odoo/api.py", line 317, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/../../13/odoo-13.0+e.20200916/odoo/addons/web_studio/models/studio_mixin.py",
line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-31>", line 2, in create
  File "/home/../../13/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/../../13/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/../../13/odoo/odoo/models.py", line 3779, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/../../13/odoo/odoo/fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 299, in _inverse_arch
    view.write(data)
  File "/home/../../13/odoo/addons/w..ite_theme_install/models/theme_models.py",
line 226, in write
    res = super(IrUiView, other_views).write(vals)
  File "/home/../../13/odoo/addons/w..ite/models/ir_ui_view.py", line
51, in write
    return super(View, self).write(vals)
  File "/home/../../13/odoo-13.0+e.20200916/odoo/addons/web_studio/models/studio_mixin.py",
line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/../../13/odoo/odoo/models.py", line 3568, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/home/../../13/odoo/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/home/../../13/odoo/odoo/addons/base/models/ir_ui_view.py",
line 406, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') %
(view_name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view view.res.partner.map
definition in web_google_maps/views/res_partner.xml
None" while parsing
/home/../../13/projects/KIK/KIK_gws_alternative_test/web_google_maps/views/res_partner.xml:2,
near
<odoo>
    <record id="view_res_partner_map" model="ir.ui.view">
        <field name="name">view.res.partner.map</field>
        <field name="model">res.partner</field>
        <field name="arch" type="xml">
            <map class="o_res_partner_map" library="geometry"
string="Map" lat="partner_latitude" lng="partner_longitude"
colors="blue:company_type=='person';green:company_type=='company';">
                <field name="id"/>
                <field name="partner_latitude"/>
                <field name="partner_longitude"/>
                <field name="company_type"/>
                <field name="color"/>
                <field name="display_name"/>
                <field name="title"/>
                <field name="email"/>
                <field name="parent_id"/>
                <field name="is_company"/>
                <field name="function"/>
                <field name="phone"/>
                <field name="street"/>
                <field name="street2"/>
                <field name="zip"/>
                <field name="city"/>
                <field name="country_id"/>
                <field name="mobile"/>
                <field name="state_id"/>
                <field name="category_id"/>
                <field name="type"/>
                <templates>
                    <t t-name="kanban-box">
                        <div class="oe_kanban_global_click
o_res_partner_kanban">
                            <div class="o_kanban_image">
                                <t t-if="record.image_small.raw_value">
                                    <img
t-att-src="kanban_image('res.partner', 'image_small',
record.id.raw_value)"/>
                                </t>
                                <t t-if="!record.image_small.raw_value">
                                    <t t-if="record.type.raw_value ===
'delivery'">
                                        <img t-att-src="_s +
&quot;/base/static/src/img/truck.png&quot;" class="o_kanban_image
oe_kanban_avatar_smallbox"/>
                                    </t>
                                    <t t-if="record.type.raw_value ===
'invoice'">
                                        <img t-att-src="_s +
&quot;/base/static/src/img/money.png&quot;" class="o_kanban_image
oe_kanban_avatar_smallbox"/>
                                    </t>
                                    <t t-if="record.type.raw_value !=
'invoice' &amp;&amp; record.type.raw_value != 'delivery'">
                                        <t
t-if="record.is_company.raw_value === true">
                                            <img t-att-src="_s +
&quot;/base/static/src/img/company_image.png&quot;"/>
                                        </t>
                                        <t
t-if="record.is_company.raw_value === false">
                                            <img t-att-src="_s +
&quot;/base/static/src/img/avatar.png&quot;"/>
                                        </t>
                                    </t>
                                </t>
                            </div>
                            <div class="oe_kanban_details">
                                <strong class="o_kanban_record_title
oe_partner_heading">
                                    <field name="display_name"/>
                                </strong>
                                <div class="o_kanban_tags_section
oe_kanban_partner_categories">
                                    <span class="oe_kanban_list_many2many">
                                        <field name="category_id"
widget="many2many_tags" options="{'color_field': 'color'}"/>
                                    </span>
                                </div>
                                <ul>
                                    <li
t-if="record.parent_id.raw_value and !record.function.raw_value">
                                        <field name="parent_id"/>
                                    </li>
                                    <li
t-if="!record.parent_id.raw_value and record.function.raw_value">
                                        <field name="function"/>
                                    </li>
                                    <li
t-if="record.parent_id.raw_value and record.function.raw_value">
                                        <field name="function"/> at
<field name="parent_id"/>
                                    </li>
                                    <li t-if="record.city.raw_value
and !record.country_id.raw_value">
                                        <field name="city"/>
                                    </li>
                                    <li t-if="!record.city.raw_value
and record.country_id.raw_value">
                                        <field name="country_id"/>
                                    </li>
                                    <li t-if="record.city.raw_value
and record.country_id.raw_value">
                                        <field name="city"/>
                ,                        <field name="country_id"/>
                                    </li>
                                    <li t-if="record.email.raw_value"
class="o_text_overflow">
                                        <field name="email"/>
                                    </li>
                                </ul>
                                <div class="oe_kanban_partner_links"/>
                            </div>
                        </div>
                    </t>
                </templates>
            </map>
        </field>
    </record>
    <record id="base.action_partner_form" model="ir.actions.act_window">
        <field name="view_mode">kanban,tree,form,map</field>
    </record>
    <record id="action_partner_form_view3" model="ir.actions.act_window.view">
        <field eval="3" name="sequence"/>
        <field name="view_mode">map</field>
        <field name="view_id" ref="view_res_partner_map"/>
        <field name="act_window_id" ref="base.action_partner_form"/>
    </record>
</odoo>

**Comment by gityopie** [comment]
@MahmoudFahmi Looks like you are using the incorrect version
<img width="677" alt="Screen Shot 2020-11-01 at 21 20 06" src="https://user-images.githubusercontent.com/3539144/97805343-15b14080-1c88-11eb-8acd-f18802d82a0a.png">

On version 13.0, the "Google map" view name has been changed to `google_map` 
https://github.com/gityopie/odoo-addons/blob/13.0/web_google_maps/views/res_partner.xml#L7
