### ISSUE TITLE
Error: QWeb2: Template 'GoogleMapView.buttons' not found

### ISSUE THREAD

**Issue by oranteso** [gityopie/odoo-addons#187]
Hello,

I am installing module crm_maps-14.0.1.0.3 for Odoo 14,

Clean installation, uploading the module, and installing

Now Map icon appears on CRM module
![image](https://user-images.githubusercontent.com/4840393/147720242-a167eb1c-9f50-4255-8290-91adb4f15ac7.png)

But I get the below error of Qweb 

Traceback:
Error: QWeb2: Template 'GoogleMapView.buttons' not found
    at Object.exception (https://odoo.eagleroofingcontractorinc.com/web/content/1396-d8fc362/web.assets_common.js:4416:7)
    at Engine._render (https://odoo.eagleroofingcontractorinc.com/web/content/1396-d8fc362/web.assets_common.js:4461:103)
    at Engine.render (https://odoo.eagleroofingcontractorinc.com/web/content/1396-d8fc362/web.assets_common.js:4457:151)
    at Class.renderButtons (https://odoo.eagleroofingcontractorinc.com/web/content/2041-bef7782/web.assets_backend.js:6608:1269)
    at Class._update (https://odoo.eagleroofingcontractorinc.com/web/content/2041-bef7782/web.assets_backend.js:1353:107)
    at Class.update (https://odoo.eagleroofingcontractorinc.com/web/content/2041-bef7782/web.assets_backend.js:1349:224)

**Comment by gityopie** [comment]
Hi @oranteso 

I don't recommend to install the module via import module,
it must be done via server configuration, put the modules on your server and then do the installation

**Comment by oranteso** [comment]
Hello Yopi,

Actually I installed the module as your recomendation.

After install the module, I was getting some error, but was solved with the most powerful technical resource... Restart! , after restart Odoo service, everything its working fine!

**Comment by gityopie** [comment]
@oranteso Yes.. Glad to hear that 
If you have any feedback don't hesitate to ping me
