### ISSUE TITLE
Error when open map view

### ISSUE THREAD

**Issue by qvinh222** [gityopie/odoo-addons#56]
I install the module for V11. After installing, I get the API for the map.
In customer list view of sale module, I see a button for map view. I click the map view button and the following error show up:
(all longitude and latitude of my res.partner is null)
Error:
Uncaught TypeError: Cannot read property 'equals' of undefined

http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3089
Traceback:
TypeError: Cannot read property 'equals' of undefined
    at http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3089:358
    at Array.forEach (<anonymous>)
    at Class._clusterAddMarker (http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3089:275)
    at Class._createMarker (http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3089:75)
    at http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3091:1674
    at Function._.each._.forEach (http://localhost:8069/web/content/755-ebd0930/web.assets_common.js:12:558)
    at Class._renderUngrouped (http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3091:1488)
    at Class._renderMarkers (http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3091:941)
    at Class._renderView (http://localhost:8069/web/content/983-0cfe138/web.assets_backend.js:3096:556)
    at Class.prototype.(anonymous function) [as _renderView] (http://localhost:8069/web/content/755-ebd0930/web.assets_common.js:3816:488)

**Comment by qvinh222** [comment]
Fixed. I must enable Map Javascript API in google cloud platform then copy the api key. => done.
