### ISSUE TITLE
'MapView.buttons' not found

### ISSUE THREAD

**Issue by qvinh222** [gityopie/odoo-addons#77]
Odoo V12:
I installed fresh new odoo v12 and test you module.
I install the module then click on Map icon (on Sale->Customer model). Following error occurs:

Uncaught Error: QWeb2: Template 'MapView.buttons' not found
http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3374
Traceback:
Error: QWeb2: Template 'MapView.buttons' not found
    at Object.exception (http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3374:7)
    at Engine._render (http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3419:103)
    at Engine.render (http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3415:151)
    at Class.renderButtons (http://localhost:8069/web/content/768-1c4f312/web.assets_backend.js:3283:638)
    at Class._renderControlPanelElements (http://localhost:8069/web/content/768-1c4f312/web.assets_backend.js:1279:175)
    at Class.start (http://localhost:8069/web/content/768-1c4f312/web.assets_backend.js:1271:1427)
    at Class.prototype.(anonymous function) [as start] (http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3537:488)
    at Class.start (http://localhost:8069/web/content/768-1c4f312/web.assets_backend.js:1522:1018)
    at Class.prototype.(anonymous function) [as start] (http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3537:488)
    at http://localhost:8069/web/content/735-9ab1e86/web.assets_common.js:3682:52

**Comment by gityopie** [comment]
Hi @qvinh222 

Thanks for reporting this issue.
Unfortunately, I could not reproduce the error on my test.

I made a video of my local installation
https://drive.google.com/open?id=1ju6_BB01lERg-eoEzdQcoPxVNkmwtIwQ
