### ISSUE TITLE
contacts_maps >>>>>>Error during installation - V11

### ISSUE THREAD

**Issue by adaxtechnology** [gityopie/odoo-addons#96]
Erro:
Aviso

Traceback (most recent call last):
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adaxtechnology/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/adaxtechnology/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adaxtechnology/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/adaxtechnology/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "view_mode" violates not-null constraint
DETAIL:  Failing row contains (1965, 3, null, null, null, f, 1, 2019-03-22 17:55:44.97663, 1, 2019-03-22 17:55:44.97663).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adaxtechnology/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adaxtechnology/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adaxtechnology/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adaxtechnology/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adaxtechnology/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adaxtechnology/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/adaxtechnology/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/adaxtechnology/modulos/interface/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adaxtechnology/modulos/interface/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adaxtechnology/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adaxtechnology/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/adaxtechnology/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adaxtechnology/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adaxtechnology/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/adaxtechnology/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adaxtechnology/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/adaxtechnology/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adaxtechnology/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/adaxtechnology/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "view_mode" violates not-null constraint
DETAIL:  Failing row contains (1965, 3, null, null, null, f, 1, 2019-03-22 17:55:44.97663, 1, 2019-03-22 17:55:44.97663).
" while parsing /opt/adaxtechnology/modulos/geo/contacts_maps/views/res_partner.xml:6, near
<record id="contacts.action_contacts_view_form" model="ir.actions.act_window.view">
        <field name="sequence" eval="3"/>
    </record>

**Comment by gityopie** [comment]
@adaxtechnology could you please provide steps to reproduce this issue?

**Comment by adaxtechnology** [comment]
I just tried to install the contacts_maps module, the other modules installed perfectly.

**Comment by gityopie** [comment]
@adaxtechnology strange, I don't have any issue installing this module
can you make sure you are in the right version?
how about install the module on fresh DB?

**Comment by adaxtechnology** [comment]
I am using ubuntu server 16.0.4.6

Odoo v11

I did the test installing on new database and had the same error.


__________________________________________________________________________________

Erro:
Aviso

Traceback (most recent call last):
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adaxtechnology/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/adaxtechnology/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adaxtechnology/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/adaxtechnology/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "view_mode" violates not-null constraint
DETAIL:  Failing row contains (18, 3, null, null, null, f, 1, 2019-03-24 21:37:15.94558, 1, 2019-03-24 21:37:15.94558).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adaxtechnology/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adaxtechnology/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adaxtechnology/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adaxtechnology/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adaxtechnology/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adaxtechnology/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/adaxtechnology/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/adaxtechnology/modulos/web/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adaxtechnology/modulos/web/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adaxtechnology/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adaxtechnology/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/opt/adaxtechnology/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adaxtechnology/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adaxtechnology/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/adaxtechnology/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/opt/adaxtechnology/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adaxtechnology/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adaxtechnology/odoo/addons/base/ir/ir_model.py", line 1487, in _update
    record = record.create(values)
  File "/opt/adaxtechnology/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adaxtechnology/odoo/models.py", line 3466, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/adaxtechnology/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/adaxtechnology/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "view_mode" violates not-null constraint
DETAIL:  Failing row contains (18, 3, null, null, null, f, 1, 2019-03-24 21:37:15.94558, 1, 2019-03-24 21:37:15.94558).
" while parsing /opt/adaxtechnology/modulos/geo/contacts_maps/views/res_partner.xml:6, near
<record id="contacts.action_contacts_view_form" model="ir.actions.act_window.view">
        <field name="sequence" eval="3"/>
    </record>

**Comment by thiago95macedo** [comment]
Problem solved, my contacts module was outdated.

**Comment by gityopie** [comment]
@thiago95macedo nice!
thanks for letting me know
